# Generated by Django 3.1.2 on 2020-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201008_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(null=True),
        ),
    ]
